DROP TABLE IF EXISTS `#__regn_reg`;
DROP TABLE IF EXISTS `#__regn_hist`;
DROP TABLE IF EXISTS `#__regn_Aktiviteter`;
DROP TABLE IF EXISTS `#__regn_bank`;
DROP TABLE IF EXISTS `#__regn_bunt`;
DROP TABLE IF EXISTS `#__regn_debitorer`;
DROP TABLE IF EXISTS `#__regn_firma`;
DROP TABLE IF EXISTS `#__regn_hist`;
DROP TABLE IF EXISTS `#__regn_kontoperiode`;
DROP TABLE IF EXISTS `#__regn_kreditorer`;
DROP TABLE IF EXISTS `#__regn_kto`;
DROP TABLE IF EXISTS `#__regn_oppstart`;
DROP TABLE IF EXISTS `#__regn_perioder`;
DROP TABLE IF EXISTS `#__regn_postnr` ;
DROP TABLE IF EXISTS `#__regn_prosjekt`;
DROP TABLE IF EXISTS `#__regn_prosj_tidslinje` ;
DROP TABLE IF EXISTS `#__regn_regnskapsar`; 
DROP TABLE IF EXISTS `#__regn_resindex` ;
DROP TABLE IF EXISTS `#__regn_resindex1`;
DROP TABLE IF EXISTS `#__regn_resindex2`;
DROP TABLE IF EXISTS `#__regn_reskontro1` ;
DROP TABLE IF EXISTS `#__regn_resmal`;
DROP TABLE IF EXISTS `#__regn_resrapport`;
DROP TABLE IF EXISTS `#__regn_Ressurs`;
DROP TABLE IF EXISTS `#__regn_trans`;
DROP TABLE IF EXISTS `#__regn_unntaksregler` ;
DROP TABLE IF EXISTS `#__regn_varer`;
DROP TABLE IF EXISTS `#__regn_Aktiviteter`;
DROP TABLE IF EXISTS `#__regn_periodesaldo`;
DROP TABLE IF EXISTS `#__regn_bilagsarter`;
DROP TABLE IF EXISTS `#__regn_kto_hittil_budsjet`;
DROP TABLE IF EXISTS `#__regn_saldo`;
DROP TABLE IF EXISTS `#__regn_sadloliste`;

